AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  multest-app

  SAM Template for MulTest-app
  Erwin R. Komen
  Radboud University Nijmegen, Faculaty of Arts, Humanities lab, TSG

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30     # Usually 10, but for 'R' it must be 30 seconds or more

Resources:
  MulTestappFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: test_list/
      Handler: labda_list.lambda_handler
      Runtime: python3.7
      Architectures:
        - x86_64
      Events:
        MultiLapp:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /list
            Method: get
  MulTestappFilter:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: test_filter/
      Handler: labda_filter.lambda_handler
      Runtime: python3.7
      Architectures:
        - x86_64
      Events:
        MultiLapp:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /filter
            Method: get


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  MulTestappApi:
    Description: "API Gateway endpoint URL for Prod stage for MulTestapp function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/list/"
  MulTestappFunction:
    Description: "MulTestapp LIST Lambda Function ARN"
    Value: !GetAtt MulTestappFunction.Arn
  MulTestappFunctionIamRole:
    Description: "Implicit IAM Role created for MulTestapp function"
    Value: !GetAtt MulTestappFunctionRole.Arn

  MulTestappFilter:
    Description: "MulTestapp FILTER Lambda Function ARN"
    Value: !GetAtt MulTestappFilter.Arn

  