AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  multil-app

  SAM Template for multil-app
  Erwin R. Komen
  Radboud University Nijmegen, Faculaty of Arts, Humanities lab, TSG

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30     # Usually 10, but for 'R' it must be 30 seconds or more

Resources:
  MultiLappList:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: multil_list/
      Handler: labda_list.lambda_handler
      Runtime: python3.7
      Architectures:
        - x86_64
      Events:
        MultiLapp:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /list
            Method: get
  MultiLappFilter:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: multil_filter/
      Handler: labda_filter.lambda_handler
      Runtime: python3.7
      Architectures:
        - x86_64
      Events:
        MultiLapp:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /filter
            Method: get
  MultiLappFeature:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: multil_feature/
      Handler: labda_feature.lambda_handler
      Runtime: python3.7
      Architectures:
        - x86_64
      Events:
        MultiLapp:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /feature
            Method: get
  MultiLappAdd:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: multil_add/
      Handler: labda_add.lambda_handler
      Runtime: python3.7
      Architectures:
        - x86_64
      Events:
        MultiLapp:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /add
            Method: post


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  MultiLappApi:
    Description: "API Gateway endpoint URL for Prod stage for MultiLapp function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/list/"
  MultiLappList:
    Description: "MultiLapp LIST Lambda Function ARN"
    Value: !GetAtt MultiLappList.Arn
  MultiLappListIamRole:
    Description: "Implicit IAM Role created for MultiLapp function"
    Value: !GetAtt MultiLappListRole.Arn

  MultiLappFilter:
    Description: "MultiLapp FILTER Lambda Function ARN"
    Value: !GetAtt MultiLappFilter.Arn

  MultiLappFeature:
    Description: "MultiLapp FEATURE Lambda Function ARN"
    Value: !GetAtt MultiLappFeature.Arn

  MultiLappAdd:
    Description: "MultiLapp ADD Lambda Function ARN"
    Value: !GetAtt MultiLappAdd.Arn



